on:
  schedule:
    # every week
    - cron: "0 0 * * 1"

  workflow_dispatch:

jobs:
  update_animes:
    runs-on: ubuntu-latest
    name: Updates README Anime List
    steps:
      - uses: actions/checkout@v2
      - uses: glup3/anilist-animes-action@v1.1.0
        with:
          ANILIST_USERNAME: 'TheInternetUser'
          HEADER_TITLE: "TheInternetUser's cool awesome Anime"
          ANIME_GRID: true
          MANGA_GRID: true
